version: "3"

services:
  springboot:
    image: registry.cn-chengdu.aliyuncs.com/1s/ocr
    ports:
      - "8080:8080"
    volumes:
      - "./tessdata:/opt/jar/tessdata"
    working_dir: /opt/jar
    container_name: ocr
    restart: always
    
# mkdir -p tessdata
# wget -O tessdata/chi_sim.traineddata  https://github.com/tesseract-ocr/tessdata_best/raw/master/chi_sim.traineddata 
# wget -O tessdata/chi_sim.traineddata  https://github.com/tesseract-ocr/tessdata_best/raw/master/chi_sim_vert.traineddata 