server:
  port: 8080


ocr:
  datasetPath: "./tessdata"




logging:
  file:
    name: logs/StreamController.log



spring:
  thymeleaf:
    suffix: .html
    mode: HTML
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8